---
downloads: ~/.ansible-downloads/

configure_sudoers: yes
configure_terminal: yes
configure_osx: yes

dotfiles_repo: https://github.com/aceyogi/dotfiles.git
dotfiles_repo_accept_hostkey: yes
dotfiles_repo_local_destination: ~/Dropbox/Development/GitHub/dotfiles
dotfiles_files:
  - .bash_profile
  - .gitconfig
  - .gitignore
  - .inputrc
  - .osx
  - .vimrc

homebrew_installed_packages:
   - ansible
   - bash-completion
   - dockutil
   - git
   - mercurial
   - packer
   - rsync
   - wget

homebrew_taps:
  - homebrew/core
  - caskroom/cask
  - homebrew/binary
  - homebrew/dupes
  - homebrew/versions

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - 1password
  - atom
  - caffeine
  - cheatsheet
  - dropbox
  - flycut
  - google-chrome
  - google-drive
  - handbrake
  - intellij-idea-ce
  - launchbar
  - nordvpn
  - nvalt
  - plex-media-server
  - skype
  - spotify
  - superduper
  - taskpaper
  - transmission
  - vagrant
  - vagrant-manager
  - virtualbox
  - vlc
  - ynab
# - mactex

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps:
  - { id: 420212497, name: "Byword" }
  - { id: 411643860, name: "DaisyDisk" }
#  - { id: 409183694, name: "Keynote" }
  - { id: 1147396723, name: "WhatsApp Desktop" }
#  - { id: 497799835, name: "Xcode" }
#  - { id: 1127487414, name: "macOS Sierra" }
mas_email: ""
mas_password: ""

dockitems_remove_all: true

dockitems_enabled:
  - name: System Preferences
    path: "/Applications/System Preferences.app"
    pos: 1
  - name: NordVPN
    path: "/Applications/NordVPN.app"
    pos: 2
  - name: Google Chrome
    path: "/Applications/Google Chrome.app"
    pos: 3
  - name: Safari
    path: "/Applications/Safari.app"
    pos: 4
  - name: Spotify
    path: "/Applications/Spotify.app"
    pos: 5
  - name: Task Paper
    path: "/Applications/TaskPaper.app"
    pos: 6
  - name: Atom
    path: "/Applications/Atom.app"
    pos: 7
  - name: Intellij IDEA CE
    path: "/Applications/IntelliJ IDEA CE.app"
    pos: 8
  - name: Plex Media Server
    path: "/Applications/Plex Media Server.app"
    pos: 9
  - name: Terminal
    path: "/Applications/Utilities/Terminal.app"
    pos: 10
