---
downloads: ~/.ansible-downloads/

configure_sudoers: yes
configure_terminal: yes
configure_osx: yes

dotfiles_repo: https://github.com/aceyogi/dotfiles.git
dotfiles_repo_accept_hostkey: yes
dotfiles_repo_local_destination: ~/Dropbox/Development/GitHub/dotfiles
dotfiles_files:
  - .bash_profile
  - .gitconfig
  - .gitignore
  - .inputrc
  - .osx
  - .vimrc

homebrew_installed_packages:
   - ansible
   - dnsmasq
   - git
   - mercurial
   - wget

homebrew_taps:
  - homebrew/core
  - caskroom/cask
  - homebrew/binary
  - homebrew/dupes
  - homebrew/versions

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - 1password
  - atom
  - caffeine
  - dropbox
  - flycut
  - google-chrome
  - google-drive
  - handbrake
  - intellij-idea-ce
  - launchbar
  - nordvpn
  - nvalt
  - plex-media-player
  - skype
  - spotify
  - superduper
  - taskpaper
  - vagrant
  - virtualbox
  - vlc
  - ynab
# - mactex

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps:
  - { id: 420212497, name: "Byword" }
  - { id: 411643860, name: "DaisyDisk" }
  - { id: 409183694, name: "Keynote" }
  - { id: 1147396723, name: "WhatsApp Desktop" }
  - { id: 497799835, name: "Xcode" }
#  - { id: 1127487414, name: "macOS Sierra" }
mas_email: ""
mas_password: ""
